// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: sistema.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenJwt      string                 `protobuf:"bytes,1,opt,name=token_jwt,json=tokenJwt,proto3" json:"token_jwt,omitempty"`
	QueryType     string                 `protobuf:"bytes,2,opt,name=query_type,json=queryType,proto3" json:"query_type,omitempty"` //ex: "ResumoClinico", "HistoricoClinico", "ResumoCoorte"
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`    //ID do paciente solicitado ou ID do projeto de pesquisa
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_sistema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRequest) GetTokenJwt() string {
	if x != nil {
		return x.TokenJwt
	}
	return ""
}

func (x *AuthRequest) GetQueryType() string {
	if x != nil {
		return x.QueryType
	}
	return ""
}

func (x *AuthRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                              // "ALLOW" ou "DENY"
	AccessLevel   string                 `protobuf:"bytes,2,opt,name=access_level,json=accessLevel,proto3" json:"access_level,omitempty"` // "FULL", "PARTIAL", "ANONYMIZED", "AGGREGATED"
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"` // "MEDICO", "ESTAGIARIO", "PESQUISADOR"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_sistema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{1}
}

func (x *AuthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AuthResponse) GetAccessLevel() string {
	if x != nil {
		return x.AccessLevel
	}
	return ""
}

func (x *AuthResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type PatientQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	PatientId     string                 `protobuf:"bytes,3,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"` // opcional (se vazio, busca por vínculo)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatientQueryRequest) Reset() {
	*x = PatientQueryRequest{}
	mi := &file_sistema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatientQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientQueryRequest) ProtoMessage() {}

func (x *PatientQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientQueryRequest.ProtoReflect.Descriptor instead.
func (*PatientQueryRequest) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{2}
}

func (x *PatientQueryRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PatientQueryRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *PatientQueryRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

type DBPatient struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdPaciente     string                 `protobuf:"bytes,1,opt,name=id_paciente,json=idPaciente,proto3" json:"id_paciente,omitempty"`
	Nome           string                 `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	DataNascimento string                 `protobuf:"bytes,3,opt,name=data_nascimento,json=dataNascimento,proto3" json:"data_nascimento,omitempty"`
	Genero         string                 `protobuf:"bytes,4,opt,name=genero,proto3" json:"genero,omitempty"`
	Cidade         string                 `protobuf:"bytes,5,opt,name=cidade,proto3" json:"cidade,omitempty"`
	Estado         string                 `protobuf:"bytes,6,opt,name=estado,proto3" json:"estado,omitempty"`
	Cpf            string                 `protobuf:"bytes,7,opt,name=cpf,proto3" json:"cpf,omitempty"`
	Cns            string                 `protobuf:"bytes,8,opt,name=cns,proto3" json:"cns,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DBPatient) Reset() {
	*x = DBPatient{}
	mi := &file_sistema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBPatient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBPatient) ProtoMessage() {}

func (x *DBPatient) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBPatient.ProtoReflect.Descriptor instead.
func (*DBPatient) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{3}
}

func (x *DBPatient) GetIdPaciente() string {
	if x != nil {
		return x.IdPaciente
	}
	return ""
}

func (x *DBPatient) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *DBPatient) GetDataNascimento() string {
	if x != nil {
		return x.DataNascimento
	}
	return ""
}

func (x *DBPatient) GetGenero() string {
	if x != nil {
		return x.Genero
	}
	return ""
}

func (x *DBPatient) GetCidade() string {
	if x != nil {
		return x.Cidade
	}
	return ""
}

func (x *DBPatient) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *DBPatient) GetCpf() string {
	if x != nil {
		return x.Cpf
	}
	return ""
}

func (x *DBPatient) GetCns() string {
	if x != nil {
		return x.Cns
	}
	return ""
}

type PatientQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patients      []*DBPatient           `protobuf:"bytes,1,rep,name=patients,proto3" json:"patients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatientQueryResponse) Reset() {
	*x = PatientQueryResponse{}
	mi := &file_sistema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatientQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientQueryResponse) ProtoMessage() {}

func (x *PatientQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientQueryResponse.ProtoReflect.Descriptor instead.
func (*PatientQueryResponse) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{4}
}

func (x *PatientQueryResponse) GetPatients() []*DBPatient {
	if x != nil {
		return x.Patients
	}
	return nil
}

type EncounterQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncounterQueryRequest) Reset() {
	*x = EncounterQueryRequest{}
	mi := &file_sistema_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncounterQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncounterQueryRequest) ProtoMessage() {}

func (x *EncounterQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncounterQueryRequest.ProtoReflect.Descriptor instead.
func (*EncounterQueryRequest) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{5}
}

func (x *EncounterQueryRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

type DBEncounter struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IdAtendimento     string                 `protobuf:"bytes,1,opt,name=id_atendimento,json=idAtendimento,proto3" json:"id_atendimento,omitempty"`
	IdPaciente        string                 `protobuf:"bytes,2,opt,name=id_paciente,json=idPaciente,proto3" json:"id_paciente,omitempty"`
	DataInicio        string                 `protobuf:"bytes,3,opt,name=data_inicio,json=dataInicio,proto3" json:"data_inicio,omitempty"`
	DataFim           string                 `protobuf:"bytes,4,opt,name=data_fim,json=dataFim,proto3" json:"data_fim,omitempty"`
	TipoAtendimento   string                 `protobuf:"bytes,5,opt,name=tipo_atendimento,json=tipoAtendimento,proto3" json:"tipo_atendimento,omitempty"`
	SetorDepartamento string                 `protobuf:"bytes,6,opt,name=setor_departamento,json=setorDepartamento,proto3" json:"setor_departamento,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DBEncounter) Reset() {
	*x = DBEncounter{}
	mi := &file_sistema_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBEncounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBEncounter) ProtoMessage() {}

func (x *DBEncounter) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBEncounter.ProtoReflect.Descriptor instead.
func (*DBEncounter) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{6}
}

func (x *DBEncounter) GetIdAtendimento() string {
	if x != nil {
		return x.IdAtendimento
	}
	return ""
}

func (x *DBEncounter) GetIdPaciente() string {
	if x != nil {
		return x.IdPaciente
	}
	return ""
}

func (x *DBEncounter) GetDataInicio() string {
	if x != nil {
		return x.DataInicio
	}
	return ""
}

func (x *DBEncounter) GetDataFim() string {
	if x != nil {
		return x.DataFim
	}
	return ""
}

func (x *DBEncounter) GetTipoAtendimento() string {
	if x != nil {
		return x.TipoAtendimento
	}
	return ""
}

func (x *DBEncounter) GetSetorDepartamento() string {
	if x != nil {
		return x.SetorDepartamento
	}
	return ""
}

type EncounterQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Encounters    []*DBEncounter         `protobuf:"bytes,1,rep,name=encounters,proto3" json:"encounters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncounterQueryResponse) Reset() {
	*x = EncounterQueryResponse{}
	mi := &file_sistema_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncounterQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncounterQueryResponse) ProtoMessage() {}

func (x *EncounterQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncounterQueryResponse.ProtoReflect.Descriptor instead.
func (*EncounterQueryResponse) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{7}
}

func (x *EncounterQueryResponse) GetEncounters() []*DBEncounter {
	if x != nil {
		return x.Encounters
	}
	return nil
}

type EventQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventQueryRequest) Reset() {
	*x = EventQueryRequest{}
	mi := &file_sistema_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventQueryRequest) ProtoMessage() {}

func (x *EventQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventQueryRequest.ProtoReflect.Descriptor instead.
func (*EventQueryRequest) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{8}
}

func (x *EventQueryRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

type DBClinicalEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IdEvento         string                 `protobuf:"bytes,1,opt,name=id_evento,json=idEvento,proto3" json:"id_evento,omitempty"`
	IdPaciente       string                 `protobuf:"bytes,2,opt,name=id_paciente,json=idPaciente,proto3" json:"id_paciente,omitempty"`
	IdAtendimento    string                 `protobuf:"bytes,3,opt,name=id_atendimento,json=idAtendimento,proto3" json:"id_atendimento,omitempty"`
	TipoEvento       string                 `protobuf:"bytes,4,opt,name=tipo_evento,json=tipoEvento,proto3" json:"tipo_evento,omitempty"`                     // "Condição", "Observação", "Medicação"
	CodigoTipoEvento string                 `protobuf:"bytes,5,opt,name=codigo_tipo_evento,json=codigoTipoEvento,proto3" json:"codigo_tipo_evento,omitempty"` // Ex: "Diabetes", "Hipertensão", "Glicemia"
	DescricaoEvento  string                 `protobuf:"bytes,6,opt,name=descricao_evento,json=descricaoEvento,proto3" json:"descricao_evento,omitempty"`
	DataEvento       string                 `protobuf:"bytes,7,opt,name=data_evento,json=dataEvento,proto3" json:"data_evento,omitempty"`
	Valor            string                 `protobuf:"bytes,8,opt,name=valor,proto3" json:"valor,omitempty"`
	UnidadeValor     string                 `protobuf:"bytes,9,opt,name=unidade_valor,json=unidadeValor,proto3" json:"unidade_valor,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DBClinicalEvent) Reset() {
	*x = DBClinicalEvent{}
	mi := &file_sistema_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBClinicalEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBClinicalEvent) ProtoMessage() {}

func (x *DBClinicalEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBClinicalEvent.ProtoReflect.Descriptor instead.
func (*DBClinicalEvent) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{9}
}

func (x *DBClinicalEvent) GetIdEvento() string {
	if x != nil {
		return x.IdEvento
	}
	return ""
}

func (x *DBClinicalEvent) GetIdPaciente() string {
	if x != nil {
		return x.IdPaciente
	}
	return ""
}

func (x *DBClinicalEvent) GetIdAtendimento() string {
	if x != nil {
		return x.IdAtendimento
	}
	return ""
}

func (x *DBClinicalEvent) GetTipoEvento() string {
	if x != nil {
		return x.TipoEvento
	}
	return ""
}

func (x *DBClinicalEvent) GetCodigoTipoEvento() string {
	if x != nil {
		return x.CodigoTipoEvento
	}
	return ""
}

func (x *DBClinicalEvent) GetDescricaoEvento() string {
	if x != nil {
		return x.DescricaoEvento
	}
	return ""
}

func (x *DBClinicalEvent) GetDataEvento() string {
	if x != nil {
		return x.DataEvento
	}
	return ""
}

func (x *DBClinicalEvent) GetValor() string {
	if x != nil {
		return x.Valor
	}
	return ""
}

func (x *DBClinicalEvent) GetUnidadeValor() string {
	if x != nil {
		return x.UnidadeValor
	}
	return ""
}

type EventQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*DBClinicalEvent     `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventQueryResponse) Reset() {
	*x = EventQueryResponse{}
	mi := &file_sistema_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventQueryResponse) ProtoMessage() {}

func (x *EventQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventQueryResponse.ProtoReflect.Descriptor instead.
func (*EventQueryResponse) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{10}
}

func (x *EventQueryResponse) GetEvents() []*DBClinicalEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type CohortQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CohortQueryRequest) Reset() {
	*x = CohortQueryRequest{}
	mi := &file_sistema_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CohortQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CohortQueryRequest) ProtoMessage() {}

func (x *CohortQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CohortQueryRequest.ProtoReflect.Descriptor instead.
func (*CohortQueryRequest) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{11}
}

func (x *CohortQueryRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type CohortQueryResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConditionCode  string                 `protobuf:"bytes,1,opt,name=condition_code,json=conditionCode,proto3" json:"condition_code,omitempty"`
	Patients       []*DBPatient           `protobuf:"bytes,2,rep,name=patients,proto3" json:"patients,omitempty"`
	RelevantEvents []*DBClinicalEvent     `protobuf:"bytes,3,rep,name=relevant_events,json=relevantEvents,proto3" json:"relevant_events,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CohortQueryResponse) Reset() {
	*x = CohortQueryResponse{}
	mi := &file_sistema_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CohortQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CohortQueryResponse) ProtoMessage() {}

func (x *CohortQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CohortQueryResponse.ProtoReflect.Descriptor instead.
func (*CohortQueryResponse) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{12}
}

func (x *CohortQueryResponse) GetConditionCode() string {
	if x != nil {
		return x.ConditionCode
	}
	return ""
}

func (x *CohortQueryResponse) GetPatients() []*DBPatient {
	if x != nil {
		return x.Patients
	}
	return nil
}

func (x *CohortQueryResponse) GetRelevantEvents() []*DBClinicalEvent {
	if x != nil {
		return x.RelevantEvents
	}
	return nil
}

type TransformRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessLevel   string                 `protobuf:"bytes,1,opt,name=access_level,json=accessLevel,proto3" json:"access_level,omitempty"` // "FULL", "PARTIAL" ou "ANONYMIZED"
	RawPatients   []*DBPatient           `protobuf:"bytes,2,rep,name=raw_patients,json=rawPatients,proto3" json:"raw_patients,omitempty"`
	RawEncounters []*DBEncounter         `protobuf:"bytes,3,rep,name=raw_encounters,json=rawEncounters,proto3" json:"raw_encounters,omitempty"`
	RawEvents     []*DBClinicalEvent     `protobuf:"bytes,4,rep,name=raw_events,json=rawEvents,proto3" json:"raw_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformRequest) Reset() {
	*x = TransformRequest{}
	mi := &file_sistema_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformRequest) ProtoMessage() {}

func (x *TransformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformRequest.ProtoReflect.Descriptor instead.
func (*TransformRequest) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{13}
}

func (x *TransformRequest) GetAccessLevel() string {
	if x != nil {
		return x.AccessLevel
	}
	return ""
}

func (x *TransformRequest) GetRawPatients() []*DBPatient {
	if x != nil {
		return x.RawPatients
	}
	return nil
}

func (x *TransformRequest) GetRawEncounters() []*DBEncounter {
	if x != nil {
		return x.RawEncounters
	}
	return nil
}

func (x *TransformRequest) GetRawEvents() []*DBClinicalEvent {
	if x != nil {
		return x.RawEvents
	}
	return nil
}

type TransformResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Patients      []*FHIRPatient           `protobuf:"bytes,1,rep,name=patients,proto3" json:"patients,omitempty"`
	Encounters    []*FHIREncounter         `protobuf:"bytes,2,rep,name=encounters,proto3" json:"encounters,omitempty"`
	Conditions    []*FHIRCondition         `protobuf:"bytes,3,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Observations  []*FHIRObservation       `protobuf:"bytes,4,rep,name=observations,proto3" json:"observations,omitempty"`
	Medications   []*FHIRMedicationRequest `protobuf:"bytes,5,rep,name=medications,proto3" json:"medications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformResponse) Reset() {
	*x = TransformResponse{}
	mi := &file_sistema_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformResponse) ProtoMessage() {}

func (x *TransformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformResponse.ProtoReflect.Descriptor instead.
func (*TransformResponse) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{14}
}

func (x *TransformResponse) GetPatients() []*FHIRPatient {
	if x != nil {
		return x.Patients
	}
	return nil
}

func (x *TransformResponse) GetEncounters() []*FHIREncounter {
	if x != nil {
		return x.Encounters
	}
	return nil
}

func (x *TransformResponse) GetConditions() []*FHIRCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *TransformResponse) GetObservations() []*FHIRObservation {
	if x != nil {
		return x.Observations
	}
	return nil
}

func (x *TransformResponse) GetMedications() []*FHIRMedicationRequest {
	if x != nil {
		return x.Medications
	}
	return nil
}

// mapeamento estruturado dos recursos FHIR solicitados
type FHIRPatient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // Sempre "Patient"
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                         // ID real ou Hash/Pseudo-ID dependendo do nível
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                     // Nome completo ou Iniciais (ex: "J. S.")
	BirthDate     string                 `protobuf:"bytes,4,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`          // Data completa, apenas Ano, ou Faixa Etária (ex: "56 anos")
	Gender        string                 `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	City          string                 `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"` // Omitido se for ANONYMIZED
	State         string                 `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	Cpf           string                 `protobuf:"bytes,8,opt,name=cpf,proto3" json:"cpf,omitempty"` // Omitido se for PARTIAL ou ANONYMIZED
	Cns           string                 `protobuf:"bytes,9,opt,name=cns,proto3" json:"cns,omitempty"` // Omitido se for PARTIAL ou ANONYMIZED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FHIRPatient) Reset() {
	*x = FHIRPatient{}
	mi := &file_sistema_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FHIRPatient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FHIRPatient) ProtoMessage() {}

func (x *FHIRPatient) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FHIRPatient.ProtoReflect.Descriptor instead.
func (*FHIRPatient) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{15}
}

func (x *FHIRPatient) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *FHIRPatient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FHIRPatient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FHIRPatient) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *FHIRPatient) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *FHIRPatient) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *FHIRPatient) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *FHIRPatient) GetCpf() string {
	if x != nil {
		return x.Cpf
	}
	return ""
}

func (x *FHIRPatient) GetCns() string {
	if x != nil {
		return x.Cns
	}
	return ""
}

type FHIREncounter struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResourceType     string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Id               string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	SubjectReference string                 `protobuf:"bytes,3,opt,name=subject_reference,json=subjectReference,proto3" json:"subject_reference,omitempty"` //referência do Paciente (ex: "Patient/hash001")
	Start            string                 `protobuf:"bytes,4,opt,name=start,proto3" json:"start,omitempty"`
	End              string                 `protobuf:"bytes,5,opt,name=end,proto3" json:"end,omitempty"`
	Type             string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`                                              // tipo de atendimento
	ServiceProvider  string                 `protobuf:"bytes,7,opt,name=service_provider,json=serviceProvider,proto3" json:"service_provider,omitempty"` // Setor/Departamento
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FHIREncounter) Reset() {
	*x = FHIREncounter{}
	mi := &file_sistema_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FHIREncounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FHIREncounter) ProtoMessage() {}

func (x *FHIREncounter) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FHIREncounter.ProtoReflect.Descriptor instead.
func (*FHIREncounter) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{16}
}

func (x *FHIREncounter) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *FHIREncounter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FHIREncounter) GetSubjectReference() string {
	if x != nil {
		return x.SubjectReference
	}
	return ""
}

func (x *FHIREncounter) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *FHIREncounter) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *FHIREncounter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FHIREncounter) GetServiceProvider() string {
	if x != nil {
		return x.ServiceProvider
	}
	return ""
}

type FHIRCondition struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResourceType     string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` //condicao
	Id               string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	SubjectReference string                 `protobuf:"bytes,3,opt,name=subject_reference,json=subjectReference,proto3" json:"subject_reference,omitempty"`
	Code             string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"` //código da comorbidade
	RecordedDate     string                 `protobuf:"bytes,5,opt,name=recorded_date,json=recordedDate,proto3" json:"recorded_date,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FHIRCondition) Reset() {
	*x = FHIRCondition{}
	mi := &file_sistema_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FHIRCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FHIRCondition) ProtoMessage() {}

func (x *FHIRCondition) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FHIRCondition.ProtoReflect.Descriptor instead.
func (*FHIRCondition) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{17}
}

func (x *FHIRCondition) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *FHIRCondition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FHIRCondition) GetSubjectReference() string {
	if x != nil {
		return x.SubjectReference
	}
	return ""
}

func (x *FHIRCondition) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *FHIRCondition) GetRecordedDate() string {
	if x != nil {
		return x.RecordedDate
	}
	return ""
}

type FHIRObservation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResourceType     string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // "Observation"
	Id               string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	SubjectReference string                 `protobuf:"bytes,3,opt,name=subject_reference,json=subjectReference,proto3" json:"subject_reference,omitempty"`
	Code             string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`   // Ex: "Glicemia", "HbA1c", "IMC"
	Value            string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"` // Valor do exame
	Unit             string                 `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`   //unidade de medida
	EffectiveDate    string                 `protobuf:"bytes,7,opt,name=effective_date,json=effectiveDate,proto3" json:"effective_date,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FHIRObservation) Reset() {
	*x = FHIRObservation{}
	mi := &file_sistema_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FHIRObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FHIRObservation) ProtoMessage() {}

func (x *FHIRObservation) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FHIRObservation.ProtoReflect.Descriptor instead.
func (*FHIRObservation) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{18}
}

func (x *FHIRObservation) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *FHIRObservation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FHIRObservation) GetSubjectReference() string {
	if x != nil {
		return x.SubjectReference
	}
	return ""
}

func (x *FHIRObservation) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *FHIRObservation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *FHIRObservation) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *FHIRObservation) GetEffectiveDate() string {
	if x != nil {
		return x.EffectiveDate
	}
	return ""
}

type FHIRMedicationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResourceType     string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // "MedicationRequest"
	Id               string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	SubjectReference string                 `protobuf:"bytes,3,opt,name=subject_reference,json=subjectReference,proto3" json:"subject_reference,omitempty"`
	MedicationCode   string                 `protobuf:"bytes,4,opt,name=medication_code,json=medicationCode,proto3" json:"medication_code,omitempty"` // Medicamento prescrito
	AuthoredOn       string                 `protobuf:"bytes,5,opt,name=authored_on,json=authoredOn,proto3" json:"authored_on,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FHIRMedicationRequest) Reset() {
	*x = FHIRMedicationRequest{}
	mi := &file_sistema_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FHIRMedicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FHIRMedicationRequest) ProtoMessage() {}

func (x *FHIRMedicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FHIRMedicationRequest.ProtoReflect.Descriptor instead.
func (*FHIRMedicationRequest) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{19}
}

func (x *FHIRMedicationRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *FHIRMedicationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FHIRMedicationRequest) GetSubjectReference() string {
	if x != nil {
		return x.SubjectReference
	}
	return ""
}

func (x *FHIRMedicationRequest) GetMedicationCode() string {
	if x != nil {
		return x.MedicationCode
	}
	return ""
}

func (x *FHIRMedicationRequest) GetAuthoredOn() string {
	if x != nil {
		return x.AuthoredOn
	}
	return ""
}

type StatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticsRequest) Reset() {
	*x = StatisticsRequest{}
	mi := &file_sistema_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsRequest) ProtoMessage() {}

func (x *StatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsRequest.ProtoReflect.Descriptor instead.
func (*StatisticsRequest) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{20}
}

func (x *StatisticsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

// Cards e tabela da tela do Pesquisador
type StatisticsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalPatients      int32                  `protobuf:"varint,1,opt,name=total_patients,json=totalPatients,proto3" json:"total_patients,omitempty"`               // Card 1: Total de Pacientes na Coorte (ex: 14000)
	GenderDistribution string                 `protobuf:"bytes,2,opt,name=gender_distribution,json=genderDistribution,proto3" json:"gender_distribution,omitempty"` // Card 2: Distribuição por Sexo (ex: "70% M | 30% H")
	AverageAge         string                 `protobuf:"bytes,3,opt,name=average_age,json=averageAge,proto3" json:"average_age,omitempty"`                         // Card 3: Média de Idade (ex: "61.5 anos")
	SampleExams        []*AnonymizedExam      `protobuf:"bytes,4,rep,name=sample_exams,json=sampleExams,proto3" json:"sample_exams,omitempty"`                      // Tabela: Amostra de Exames Anonimizados
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StatisticsResponse) Reset() {
	*x = StatisticsResponse{}
	mi := &file_sistema_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsResponse) ProtoMessage() {}

func (x *StatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsResponse.ProtoReflect.Descriptor instead.
func (*StatisticsResponse) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{21}
}

func (x *StatisticsResponse) GetTotalPatients() int32 {
	if x != nil {
		return x.TotalPatients
	}
	return 0
}

func (x *StatisticsResponse) GetGenderDistribution() string {
	if x != nil {
		return x.GenderDistribution
	}
	return ""
}

func (x *StatisticsResponse) GetAverageAge() string {
	if x != nil {
		return x.AverageAge
	}
	return ""
}

func (x *StatisticsResponse) GetSampleExams() []*AnonymizedExam {
	if x != nil {
		return x.SampleExams
	}
	return nil
}

type AnonymizedExam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PseudoId      string                 `protobuf:"bytes,1,opt,name=pseudo_id,json=pseudoId,proto3" json:"pseudo_id,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Gender        string                 `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Hba1C         string                 `protobuf:"bytes,4,opt,name=hba1c,proto3" json:"hba1c,omitempty"`
	Glicemia      string                 `protobuf:"bytes,5,opt,name=glicemia,proto3" json:"glicemia,omitempty"`
	Imc           string                 `protobuf:"bytes,6,opt,name=imc,proto3" json:"imc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnonymizedExam) Reset() {
	*x = AnonymizedExam{}
	mi := &file_sistema_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnonymizedExam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnonymizedExam) ProtoMessage() {}

func (x *AnonymizedExam) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnonymizedExam.ProtoReflect.Descriptor instead.
func (*AnonymizedExam) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{22}
}

func (x *AnonymizedExam) GetPseudoId() string {
	if x != nil {
		return x.PseudoId
	}
	return ""
}

func (x *AnonymizedExam) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *AnonymizedExam) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *AnonymizedExam) GetHba1C() string {
	if x != nil {
		return x.Hba1C
	}
	return ""
}

func (x *AnonymizedExam) GetGlicemia() string {
	if x != nil {
		return x.Glicemia
	}
	return ""
}

func (x *AnonymizedExam) GetImc() string {
	if x != nil {
		return x.Imc
	}
	return ""
}

var File_sistema_proto protoreflect.FileDescriptor

const file_sistema_proto_rawDesc = "" +
	"\n" +
	"\rsistema.proto\x12\x0fclinical_system\"f\n" +
	"\vAuthRequest\x12\x1b\n" +
	"\ttoken_jwt\x18\x01 \x01(\tR\btokenJwt\x12\x1d\n" +
	"\n" +
	"query_type\x18\x02 \x01(\tR\tqueryType\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\"y\n" +
	"\fAuthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12!\n" +
	"\faccess_level\x18\x02 \x01(\tR\vaccessLevel\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"d\n" +
	"\x13PatientQueryRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x03 \x01(\tR\tpatientId\"\xd5\x01\n" +
	"\tDBPatient\x12\x1f\n" +
	"\vid_paciente\x18\x01 \x01(\tR\n" +
	"idPaciente\x12\x12\n" +
	"\x04nome\x18\x02 \x01(\tR\x04nome\x12'\n" +
	"\x0fdata_nascimento\x18\x03 \x01(\tR\x0edataNascimento\x12\x16\n" +
	"\x06genero\x18\x04 \x01(\tR\x06genero\x12\x16\n" +
	"\x06cidade\x18\x05 \x01(\tR\x06cidade\x12\x16\n" +
	"\x06estado\x18\x06 \x01(\tR\x06estado\x12\x10\n" +
	"\x03cpf\x18\a \x01(\tR\x03cpf\x12\x10\n" +
	"\x03cns\x18\b \x01(\tR\x03cns\"N\n" +
	"\x14PatientQueryResponse\x126\n" +
	"\bpatients\x18\x01 \x03(\v2\x1a.clinical_system.DBPatientR\bpatients\"6\n" +
	"\x15EncounterQueryRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\"\xeb\x01\n" +
	"\vDBEncounter\x12%\n" +
	"\x0eid_atendimento\x18\x01 \x01(\tR\ridAtendimento\x12\x1f\n" +
	"\vid_paciente\x18\x02 \x01(\tR\n" +
	"idPaciente\x12\x1f\n" +
	"\vdata_inicio\x18\x03 \x01(\tR\n" +
	"dataInicio\x12\x19\n" +
	"\bdata_fim\x18\x04 \x01(\tR\adataFim\x12)\n" +
	"\x10tipo_atendimento\x18\x05 \x01(\tR\x0ftipoAtendimento\x12-\n" +
	"\x12setor_departamento\x18\x06 \x01(\tR\x11setorDepartamento\"V\n" +
	"\x16EncounterQueryResponse\x12<\n" +
	"\n" +
	"encounters\x18\x01 \x03(\v2\x1c.clinical_system.DBEncounterR\n" +
	"encounters\"2\n" +
	"\x11EventQueryRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\"\xcc\x02\n" +
	"\x0fDBClinicalEvent\x12\x1b\n" +
	"\tid_evento\x18\x01 \x01(\tR\bidEvento\x12\x1f\n" +
	"\vid_paciente\x18\x02 \x01(\tR\n" +
	"idPaciente\x12%\n" +
	"\x0eid_atendimento\x18\x03 \x01(\tR\ridAtendimento\x12\x1f\n" +
	"\vtipo_evento\x18\x04 \x01(\tR\n" +
	"tipoEvento\x12,\n" +
	"\x12codigo_tipo_evento\x18\x05 \x01(\tR\x10codigoTipoEvento\x12)\n" +
	"\x10descricao_evento\x18\x06 \x01(\tR\x0fdescricaoEvento\x12\x1f\n" +
	"\vdata_evento\x18\a \x01(\tR\n" +
	"dataEvento\x12\x14\n" +
	"\x05valor\x18\b \x01(\tR\x05valor\x12#\n" +
	"\runidade_valor\x18\t \x01(\tR\funidadeValor\"N\n" +
	"\x12EventQueryResponse\x128\n" +
	"\x06events\x18\x01 \x03(\v2 .clinical_system.DBClinicalEventR\x06events\"3\n" +
	"\x12CohortQueryRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"\xbf\x01\n" +
	"\x13CohortQueryResponse\x12%\n" +
	"\x0econdition_code\x18\x01 \x01(\tR\rconditionCode\x126\n" +
	"\bpatients\x18\x02 \x03(\v2\x1a.clinical_system.DBPatientR\bpatients\x12I\n" +
	"\x0frelevant_events\x18\x03 \x03(\v2 .clinical_system.DBClinicalEventR\x0erelevantEvents\"\xfa\x01\n" +
	"\x10TransformRequest\x12!\n" +
	"\faccess_level\x18\x01 \x01(\tR\vaccessLevel\x12=\n" +
	"\fraw_patients\x18\x02 \x03(\v2\x1a.clinical_system.DBPatientR\vrawPatients\x12C\n" +
	"\x0eraw_encounters\x18\x03 \x03(\v2\x1c.clinical_system.DBEncounterR\rrawEncounters\x12?\n" +
	"\n" +
	"raw_events\x18\x04 \x03(\v2 .clinical_system.DBClinicalEventR\trawEvents\"\xdd\x02\n" +
	"\x11TransformResponse\x128\n" +
	"\bpatients\x18\x01 \x03(\v2\x1c.clinical_system.FHIRPatientR\bpatients\x12>\n" +
	"\n" +
	"encounters\x18\x02 \x03(\v2\x1e.clinical_system.FHIREncounterR\n" +
	"encounters\x12>\n" +
	"\n" +
	"conditions\x18\x03 \x03(\v2\x1e.clinical_system.FHIRConditionR\n" +
	"conditions\x12D\n" +
	"\fobservations\x18\x04 \x03(\v2 .clinical_system.FHIRObservationR\fobservations\x12H\n" +
	"\vmedications\x18\x05 \x03(\v2&.clinical_system.FHIRMedicationRequestR\vmedications\"\xdb\x01\n" +
	"\vFHIRPatient\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x04 \x01(\tR\tbirthDate\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12\x12\n" +
	"\x04city\x18\x06 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\a \x01(\tR\x05state\x12\x10\n" +
	"\x03cpf\x18\b \x01(\tR\x03cpf\x12\x10\n" +
	"\x03cns\x18\t \x01(\tR\x03cns\"\xd8\x01\n" +
	"\rFHIREncounter\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12+\n" +
	"\x11subject_reference\x18\x03 \x01(\tR\x10subjectReference\x12\x14\n" +
	"\x05start\x18\x04 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x05 \x01(\tR\x03end\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12)\n" +
	"\x10service_provider\x18\a \x01(\tR\x0fserviceProvider\"\xaa\x01\n" +
	"\rFHIRCondition\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12+\n" +
	"\x11subject_reference\x18\x03 \x01(\tR\x10subjectReference\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12#\n" +
	"\rrecorded_date\x18\x05 \x01(\tR\frecordedDate\"\xd8\x01\n" +
	"\x0fFHIRObservation\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12+\n" +
	"\x11subject_reference\x18\x03 \x01(\tR\x10subjectReference\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\tR\x04unit\x12%\n" +
	"\x0eeffective_date\x18\a \x01(\tR\reffectiveDate\"\xc3\x01\n" +
	"\x15FHIRMedicationRequest\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12+\n" +
	"\x11subject_reference\x18\x03 \x01(\tR\x10subjectReference\x12'\n" +
	"\x0fmedication_code\x18\x04 \x01(\tR\x0emedicationCode\x12\x1f\n" +
	"\vauthored_on\x18\x05 \x01(\tR\n" +
	"authoredOn\"2\n" +
	"\x11StatisticsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"\xd1\x01\n" +
	"\x12StatisticsResponse\x12%\n" +
	"\x0etotal_patients\x18\x01 \x01(\x05R\rtotalPatients\x12/\n" +
	"\x13gender_distribution\x18\x02 \x01(\tR\x12genderDistribution\x12\x1f\n" +
	"\vaverage_age\x18\x03 \x01(\tR\n" +
	"averageAge\x12B\n" +
	"\fsample_exams\x18\x04 \x03(\v2\x1f.clinical_system.AnonymizedExamR\vsampleExams\"\x9b\x01\n" +
	"\x0eAnonymizedExam\x12\x1b\n" +
	"\tpseudo_id\x18\x01 \x01(\tR\bpseudoId\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\tR\x06gender\x12\x14\n" +
	"\x05hba1c\x18\x04 \x01(\tR\x05hba1c\x12\x1a\n" +
	"\bglicemia\x18\x05 \x01(\tR\bglicemia\x12\x10\n" +
	"\x03imc\x18\x06 \x01(\tR\x03imc2e\n" +
	"\x14AuthorizationService\x12M\n" +
	"\x0eAuthorizeQuery\x12\x1c.clinical_system.AuthRequest\x1a\x1d.clinical_system.AuthResponse2\x94\x03\n" +
	"\x12PatientDataService\x12\\\n" +
	"\rFetchPatients\x12$.clinical_system.PatientQueryRequest\x1a%.clinical_system.PatientQueryResponse\x12b\n" +
	"\x0fFetchEncounters\x12&.clinical_system.EncounterQueryRequest\x1a'.clinical_system.EncounterQueryResponse\x12^\n" +
	"\x13FetchClinicalEvents\x12\".clinical_system.EventQueryRequest\x1a#.clinical_system.EventQueryResponse\x12\\\n" +
	"\x0fFetchCohortData\x12#.clinical_system.CohortQueryRequest\x1a$.clinical_system.CohortQueryResponse2\xd0\x01\n" +
	"\x14DataTransformService\x12X\n" +
	"\x0fTransformToFHIR\x12!.clinical_system.TransformRequest\x1a\".clinical_system.TransformResponse\x12^\n" +
	"\x13GetCohortStatistics\x12\".clinical_system.StatisticsRequest\x1a#.clinical_system.StatisticsResponseB&\n" +
	"\x19br.unb.gama.pspd.clinicalP\x01Z\a./protob\x06proto3"

var (
	file_sistema_proto_rawDescOnce sync.Once
	file_sistema_proto_rawDescData []byte
)

func file_sistema_proto_rawDescGZIP() []byte {
	file_sistema_proto_rawDescOnce.Do(func() {
		file_sistema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sistema_proto_rawDesc), len(file_sistema_proto_rawDesc)))
	})
	return file_sistema_proto_rawDescData
}

var file_sistema_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_sistema_proto_goTypes = []any{
	(*AuthRequest)(nil),            // 0: clinical_system.AuthRequest
	(*AuthResponse)(nil),           // 1: clinical_system.AuthResponse
	(*PatientQueryRequest)(nil),    // 2: clinical_system.PatientQueryRequest
	(*DBPatient)(nil),              // 3: clinical_system.DBPatient
	(*PatientQueryResponse)(nil),   // 4: clinical_system.PatientQueryResponse
	(*EncounterQueryRequest)(nil),  // 5: clinical_system.EncounterQueryRequest
	(*DBEncounter)(nil),            // 6: clinical_system.DBEncounter
	(*EncounterQueryResponse)(nil), // 7: clinical_system.EncounterQueryResponse
	(*EventQueryRequest)(nil),      // 8: clinical_system.EventQueryRequest
	(*DBClinicalEvent)(nil),        // 9: clinical_system.DBClinicalEvent
	(*EventQueryResponse)(nil),     // 10: clinical_system.EventQueryResponse
	(*CohortQueryRequest)(nil),     // 11: clinical_system.CohortQueryRequest
	(*CohortQueryResponse)(nil),    // 12: clinical_system.CohortQueryResponse
	(*TransformRequest)(nil),       // 13: clinical_system.TransformRequest
	(*TransformResponse)(nil),      // 14: clinical_system.TransformResponse
	(*FHIRPatient)(nil),            // 15: clinical_system.FHIRPatient
	(*FHIREncounter)(nil),          // 16: clinical_system.FHIREncounter
	(*FHIRCondition)(nil),          // 17: clinical_system.FHIRCondition
	(*FHIRObservation)(nil),        // 18: clinical_system.FHIRObservation
	(*FHIRMedicationRequest)(nil),  // 19: clinical_system.FHIRMedicationRequest
	(*StatisticsRequest)(nil),      // 20: clinical_system.StatisticsRequest
	(*StatisticsResponse)(nil),     // 21: clinical_system.StatisticsResponse
	(*AnonymizedExam)(nil),         // 22: clinical_system.AnonymizedExam
}
var file_sistema_proto_depIdxs = []int32{
	3,  // 0: clinical_system.PatientQueryResponse.patients:type_name -> clinical_system.DBPatient
	6,  // 1: clinical_system.EncounterQueryResponse.encounters:type_name -> clinical_system.DBEncounter
	9,  // 2: clinical_system.EventQueryResponse.events:type_name -> clinical_system.DBClinicalEvent
	3,  // 3: clinical_system.CohortQueryResponse.patients:type_name -> clinical_system.DBPatient
	9,  // 4: clinical_system.CohortQueryResponse.relevant_events:type_name -> clinical_system.DBClinicalEvent
	3,  // 5: clinical_system.TransformRequest.raw_patients:type_name -> clinical_system.DBPatient
	6,  // 6: clinical_system.TransformRequest.raw_encounters:type_name -> clinical_system.DBEncounter
	9,  // 7: clinical_system.TransformRequest.raw_events:type_name -> clinical_system.DBClinicalEvent
	15, // 8: clinical_system.TransformResponse.patients:type_name -> clinical_system.FHIRPatient
	16, // 9: clinical_system.TransformResponse.encounters:type_name -> clinical_system.FHIREncounter
	17, // 10: clinical_system.TransformResponse.conditions:type_name -> clinical_system.FHIRCondition
	18, // 11: clinical_system.TransformResponse.observations:type_name -> clinical_system.FHIRObservation
	19, // 12: clinical_system.TransformResponse.medications:type_name -> clinical_system.FHIRMedicationRequest
	22, // 13: clinical_system.StatisticsResponse.sample_exams:type_name -> clinical_system.AnonymizedExam
	0,  // 14: clinical_system.AuthorizationService.AuthorizeQuery:input_type -> clinical_system.AuthRequest
	2,  // 15: clinical_system.PatientDataService.FetchPatients:input_type -> clinical_system.PatientQueryRequest
	5,  // 16: clinical_system.PatientDataService.FetchEncounters:input_type -> clinical_system.EncounterQueryRequest
	8,  // 17: clinical_system.PatientDataService.FetchClinicalEvents:input_type -> clinical_system.EventQueryRequest
	11, // 18: clinical_system.PatientDataService.FetchCohortData:input_type -> clinical_system.CohortQueryRequest
	13, // 19: clinical_system.DataTransformService.TransformToFHIR:input_type -> clinical_system.TransformRequest
	20, // 20: clinical_system.DataTransformService.GetCohortStatistics:input_type -> clinical_system.StatisticsRequest
	1,  // 21: clinical_system.AuthorizationService.AuthorizeQuery:output_type -> clinical_system.AuthResponse
	4,  // 22: clinical_system.PatientDataService.FetchPatients:output_type -> clinical_system.PatientQueryResponse
	7,  // 23: clinical_system.PatientDataService.FetchEncounters:output_type -> clinical_system.EncounterQueryResponse
	10, // 24: clinical_system.PatientDataService.FetchClinicalEvents:output_type -> clinical_system.EventQueryResponse
	12, // 25: clinical_system.PatientDataService.FetchCohortData:output_type -> clinical_system.CohortQueryResponse
	14, // 26: clinical_system.DataTransformService.TransformToFHIR:output_type -> clinical_system.TransformResponse
	21, // 27: clinical_system.DataTransformService.GetCohortStatistics:output_type -> clinical_system.StatisticsResponse
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_sistema_proto_init() }
func file_sistema_proto_init() {
	if File_sistema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sistema_proto_rawDesc), len(file_sistema_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_sistema_proto_goTypes,
		DependencyIndexes: file_sistema_proto_depIdxs,
		MessageInfos:      file_sistema_proto_msgTypes,
	}.Build()
	File_sistema_proto = out.File
	file_sistema_proto_goTypes = nil
	file_sistema_proto_depIdxs = nil
}
