// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.1
// source: sistema.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthorizationService_AuthorizeQuery_FullMethodName = "/clinical_system.AuthorizationService/AuthorizeQuery"
)

// AuthorizationServiceClient is the client API for AuthorizationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// verifica permissões e regras de escopo
type AuthorizationServiceClient interface {
	AuthorizeQuery(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type authorizationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthorizationServiceClient(cc grpc.ClientConnInterface) AuthorizationServiceClient {
	return &authorizationServiceClient{cc}
}

func (c *authorizationServiceClient) AuthorizeQuery(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, AuthorizationService_AuthorizeQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorizationServiceServer is the server API for AuthorizationService service.
// All implementations must embed UnimplementedAuthorizationServiceServer
// for forward compatibility.
//
// verifica permissões e regras de escopo
type AuthorizationServiceServer interface {
	AuthorizeQuery(context.Context, *AuthRequest) (*AuthResponse, error)
	mustEmbedUnimplementedAuthorizationServiceServer()
}

// UnimplementedAuthorizationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthorizationServiceServer struct{}

func (UnimplementedAuthorizationServiceServer) AuthorizeQuery(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthorizeQuery not implemented")
}
func (UnimplementedAuthorizationServiceServer) mustEmbedUnimplementedAuthorizationServiceServer() {}
func (UnimplementedAuthorizationServiceServer) testEmbeddedByValue()                              {}

// UnsafeAuthorizationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthorizationServiceServer will
// result in compilation errors.
type UnsafeAuthorizationServiceServer interface {
	mustEmbedUnimplementedAuthorizationServiceServer()
}

func RegisterAuthorizationServiceServer(s grpc.ServiceRegistrar, srv AuthorizationServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthorizationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthorizationService_ServiceDesc, srv)
}

func _AuthorizationService_AuthorizeQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServiceServer).AuthorizeQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorizationService_AuthorizeQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServiceServer).AuthorizeQuery(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthorizationService_ServiceDesc is the grpc.ServiceDesc for AuthorizationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthorizationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clinical_system.AuthorizationService",
	HandlerType: (*AuthorizationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthorizeQuery",
			Handler:    _AuthorizationService_AuthorizeQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sistema.proto",
}

const (
	PatientDataService_FetchPatients_FullMethodName       = "/clinical_system.PatientDataService/FetchPatients"
	PatientDataService_FetchEncounters_FullMethodName     = "/clinical_system.PatientDataService/FetchEncounters"
	PatientDataService_FetchClinicalEvents_FullMethodName = "/clinical_system.PatientDataService/FetchClinicalEvents"
	PatientDataService_FetchCohortData_FullMethodName     = "/clinical_system.PatientDataService/FetchCohortData"
)

// PatientDataServiceClient is the client API for PatientDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// consultas SQL puras ao PostgreSQL
type PatientDataServiceClient interface {
	FetchPatients(ctx context.Context, in *PatientQueryRequest, opts ...grpc.CallOption) (*PatientQueryResponse, error)
	FetchEncounters(ctx context.Context, in *EncounterQueryRequest, opts ...grpc.CallOption) (*EncounterQueryResponse, error)
	FetchClinicalEvents(ctx context.Context, in *EventQueryRequest, opts ...grpc.CallOption) (*EventQueryResponse, error)
	FetchCohortData(ctx context.Context, in *CohortQueryRequest, opts ...grpc.CallOption) (*CohortQueryResponse, error)
}

type patientDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPatientDataServiceClient(cc grpc.ClientConnInterface) PatientDataServiceClient {
	return &patientDataServiceClient{cc}
}

func (c *patientDataServiceClient) FetchPatients(ctx context.Context, in *PatientQueryRequest, opts ...grpc.CallOption) (*PatientQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatientQueryResponse)
	err := c.cc.Invoke(ctx, PatientDataService_FetchPatients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patientDataServiceClient) FetchEncounters(ctx context.Context, in *EncounterQueryRequest, opts ...grpc.CallOption) (*EncounterQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncounterQueryResponse)
	err := c.cc.Invoke(ctx, PatientDataService_FetchEncounters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patientDataServiceClient) FetchClinicalEvents(ctx context.Context, in *EventQueryRequest, opts ...grpc.CallOption) (*EventQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventQueryResponse)
	err := c.cc.Invoke(ctx, PatientDataService_FetchClinicalEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patientDataServiceClient) FetchCohortData(ctx context.Context, in *CohortQueryRequest, opts ...grpc.CallOption) (*CohortQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CohortQueryResponse)
	err := c.cc.Invoke(ctx, PatientDataService_FetchCohortData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PatientDataServiceServer is the server API for PatientDataService service.
// All implementations must embed UnimplementedPatientDataServiceServer
// for forward compatibility.
//
// consultas SQL puras ao PostgreSQL
type PatientDataServiceServer interface {
	FetchPatients(context.Context, *PatientQueryRequest) (*PatientQueryResponse, error)
	FetchEncounters(context.Context, *EncounterQueryRequest) (*EncounterQueryResponse, error)
	FetchClinicalEvents(context.Context, *EventQueryRequest) (*EventQueryResponse, error)
	FetchCohortData(context.Context, *CohortQueryRequest) (*CohortQueryResponse, error)
	mustEmbedUnimplementedPatientDataServiceServer()
}

// UnimplementedPatientDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPatientDataServiceServer struct{}

func (UnimplementedPatientDataServiceServer) FetchPatients(context.Context, *PatientQueryRequest) (*PatientQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchPatients not implemented")
}
func (UnimplementedPatientDataServiceServer) FetchEncounters(context.Context, *EncounterQueryRequest) (*EncounterQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchEncounters not implemented")
}
func (UnimplementedPatientDataServiceServer) FetchClinicalEvents(context.Context, *EventQueryRequest) (*EventQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchClinicalEvents not implemented")
}
func (UnimplementedPatientDataServiceServer) FetchCohortData(context.Context, *CohortQueryRequest) (*CohortQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchCohortData not implemented")
}
func (UnimplementedPatientDataServiceServer) mustEmbedUnimplementedPatientDataServiceServer() {}
func (UnimplementedPatientDataServiceServer) testEmbeddedByValue()                            {}

// UnsafePatientDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PatientDataServiceServer will
// result in compilation errors.
type UnsafePatientDataServiceServer interface {
	mustEmbedUnimplementedPatientDataServiceServer()
}

func RegisterPatientDataServiceServer(s grpc.ServiceRegistrar, srv PatientDataServiceServer) {
	// If the following call panics, it indicates UnimplementedPatientDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PatientDataService_ServiceDesc, srv)
}

func _PatientDataService_FetchPatients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatientQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientDataServiceServer).FetchPatients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatientDataService_FetchPatients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientDataServiceServer).FetchPatients(ctx, req.(*PatientQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatientDataService_FetchEncounters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncounterQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientDataServiceServer).FetchEncounters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatientDataService_FetchEncounters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientDataServiceServer).FetchEncounters(ctx, req.(*EncounterQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatientDataService_FetchClinicalEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientDataServiceServer).FetchClinicalEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatientDataService_FetchClinicalEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientDataServiceServer).FetchClinicalEvents(ctx, req.(*EventQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatientDataService_FetchCohortData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CohortQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientDataServiceServer).FetchCohortData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatientDataService_FetchCohortData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientDataServiceServer).FetchCohortData(ctx, req.(*CohortQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PatientDataService_ServiceDesc is the grpc.ServiceDesc for PatientDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PatientDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clinical_system.PatientDataService",
	HandlerType: (*PatientDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchPatients",
			Handler:    _PatientDataService_FetchPatients_Handler,
		},
		{
			MethodName: "FetchEncounters",
			Handler:    _PatientDataService_FetchEncounters_Handler,
		},
		{
			MethodName: "FetchClinicalEvents",
			Handler:    _PatientDataService_FetchClinicalEvents_Handler,
		},
		{
			MethodName: "FetchCohortData",
			Handler:    _PatientDataService_FetchCohortData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sistema.proto",
}

const (
	DataTransformService_TransformToFHIR_FullMethodName     = "/clinical_system.DataTransformService/TransformToFHIR"
	DataTransformService_GetCohortStatistics_FullMethodName = "/clinical_system.DataTransformService/GetCohortStatistics"
)

// DataTransformServiceClient is the client API for DataTransformService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// anonimização, agregação e mapeamento FHIR
type DataTransformServiceClient interface {
	TransformToFHIR(ctx context.Context, in *TransformRequest, opts ...grpc.CallOption) (*TransformResponse, error)
	GetCohortStatistics(ctx context.Context, in *StatisticsRequest, opts ...grpc.CallOption) (*StatisticsResponse, error)
}

type dataTransformServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataTransformServiceClient(cc grpc.ClientConnInterface) DataTransformServiceClient {
	return &dataTransformServiceClient{cc}
}

func (c *dataTransformServiceClient) TransformToFHIR(ctx context.Context, in *TransformRequest, opts ...grpc.CallOption) (*TransformResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransformResponse)
	err := c.cc.Invoke(ctx, DataTransformService_TransformToFHIR_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataTransformServiceClient) GetCohortStatistics(ctx context.Context, in *StatisticsRequest, opts ...grpc.CallOption) (*StatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatisticsResponse)
	err := c.cc.Invoke(ctx, DataTransformService_GetCohortStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataTransformServiceServer is the server API for DataTransformService service.
// All implementations must embed UnimplementedDataTransformServiceServer
// for forward compatibility.
//
// anonimização, agregação e mapeamento FHIR
type DataTransformServiceServer interface {
	TransformToFHIR(context.Context, *TransformRequest) (*TransformResponse, error)
	GetCohortStatistics(context.Context, *StatisticsRequest) (*StatisticsResponse, error)
	mustEmbedUnimplementedDataTransformServiceServer()
}

// UnimplementedDataTransformServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataTransformServiceServer struct{}

func (UnimplementedDataTransformServiceServer) TransformToFHIR(context.Context, *TransformRequest) (*TransformResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransformToFHIR not implemented")
}
func (UnimplementedDataTransformServiceServer) GetCohortStatistics(context.Context, *StatisticsRequest) (*StatisticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCohortStatistics not implemented")
}
func (UnimplementedDataTransformServiceServer) mustEmbedUnimplementedDataTransformServiceServer() {}
func (UnimplementedDataTransformServiceServer) testEmbeddedByValue()                              {}

// UnsafeDataTransformServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataTransformServiceServer will
// result in compilation errors.
type UnsafeDataTransformServiceServer interface {
	mustEmbedUnimplementedDataTransformServiceServer()
}

func RegisterDataTransformServiceServer(s grpc.ServiceRegistrar, srv DataTransformServiceServer) {
	// If the following call panics, it indicates UnimplementedDataTransformServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataTransformService_ServiceDesc, srv)
}

func _DataTransformService_TransformToFHIR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransformRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataTransformServiceServer).TransformToFHIR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataTransformService_TransformToFHIR_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataTransformServiceServer).TransformToFHIR(ctx, req.(*TransformRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataTransformService_GetCohortStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataTransformServiceServer).GetCohortStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataTransformService_GetCohortStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataTransformServiceServer).GetCohortStatistics(ctx, req.(*StatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataTransformService_ServiceDesc is the grpc.ServiceDesc for DataTransformService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataTransformService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clinical_system.DataTransformService",
	HandlerType: (*DataTransformServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransformToFHIR",
			Handler:    _DataTransformService_TransformToFHIR_Handler,
		},
		{
			MethodName: "GetCohortStatistics",
			Handler:    _DataTransformService_GetCohortStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sistema.proto",
}
