apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: grupo-4
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
      annotations:
        description: "API Gateway Node.js"
    spec:
      containers:
        - name: api-gateway
          image: artmendy/api-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: pspd-secrets
                  key: jwt-secret
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:8081"
            - name: PATIENT_DATA_SERVICE_URL
              value: "http://patient-data:8082"
            - name: DATA_TRANSFORM_SERVICE_URL
              value: "http://data-transform:8083"
            - name: KEYCLOAK_URL
              value: "https://kiriland.unb.br/keycloak"
            - name: KEYCLOAK_REALM
              value: "grupo04"
            - name: PORT
              value: "8000"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: grupo-4
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-hpa
  namespace: grupo-4
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
