apiVersion: v1
kind: Secret
metadata:
  name: pspd-secrets
  namespace: grupo-04
type: Opaque
stringData:
  jwt-secret: "muda_antes_de_subir"
  postgres-user: "muda_antes_de_subir"
  postgres-password: "muda_antes_de_subir"
  postgres-db: "muda_antes_de_subir"
  postgres-host: "192.168.122.1"
